# fly.toml app configuration file generated for restaurant-picker-server on 2023-08-16T13:36:48+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restaurant-picker-server"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = 3000
  HOST = "0.0.0.0"
